### ISSUE TITLE
History support/integration?

### ISSUE THREAD

**Issue by nanjizal** [haxetink/tink_url#18]
Back2dos

I was trying to navigate from loaded markdown pages, think I need to history.pushState to make **github.io** re-evaluate and load in the #page I set ( or add  \[link]\(index.html?dummy=...#page ) ).  Do you have  a suggested simple approach for history that works with tink_url ? I saw Jason has a pushstate library but perhaps overkill?  Would just using normal js.html.History be good approach would some history be appropriate for tink_url ?

Cheer ;j

**Comment by back2dos** [comment]
Yeah, that's really quite a bit outside the scope of this lib, which is really for parsing/composing/manipulating urls on any platform. 

As for fiddling with the url in the browser, I frankly just use the url's hash, `window.location.hash` in the browser, because I never had the nerve to get familiar with the history API. But if you want to use it and Jason has a nice library for it, then it might be fine. Kevin also made [a lib](https://github.com/kevinresol/spectatory) but it's specifically aimed at tink_state / coconut.
