### ISSUE TITLE
Multiple host

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_url#4]
Will it be considered to support multiple host names (e.g. `mongodb://host1:27017,host2:27017`)?

**Comment by back2dos** [comment]
Oh boy. Hmm. I wouldn't really want to change URLs to have multiple hosts, because the library is really mostly focused on HTTP URLs and that would be kind of weird. Would a `static function parseMultiHost(s:String):Array<Url>` work for you?

An alternative would be to build a specific URI-type for mongodb and just reuse the individual parts like `tink.url.Host`, `tink.url.Path`, etc. but allows for multiple hosts and has appropriate implicit conversion from and to `tink.Url` (converting to a simple url could just pick the first host).

**Comment by kevinresol** [comment]
What if I add a field in UrlParts that is `hosts:Array<Host>` and keep the original `host:Host` which is simply the first item in `hosts`?

**Comment by back2dos** [comment]
My issue with that is that technically it will recognize `http://google.com,bing.com/` as a valid URL and that's impractical.
